# reV Project Points

[reV Gen](https://nrel.github.io/reV/reV/reV.generation.generation.html#reV.generation.generation.Gen)
and [reV Econ](https://nrel.github.io/reV/reV/reV.econ.econ.html#reV.econ.econ.Econ)
use [Project Points](https://nrel.github.io/reV/reV/reV.config.project_points.html#reV.config.project_points.ProjectPoints) to define which resource sites (`gids`) to run through
[PySAM](https://pysam.readthedocs.io/en/latest/) and how.

At its most basic Project Points consists of the resource `gid`s and the
`SAM` configuration file associated it. This can be definited in a variety
of ways:

1) From a project points .csv and a single or dictionary of ``SAM``
   configuration files:

In [1]:
import os
from reV import TESTDATADIR
from reV.config.project_points import ProjectPoints

fpp = os.path.join(TESTDATADIR, 'project_points/pp_offshore.csv')
sam_files = {'onshore': os.path.join(
                TESTDATADIR, 'SAM/wind_gen_standard_losses_0.json'),
                'offshore': os.path.join(
                TESTDATADIR, 'SAM/wind_gen_standard_losses_1.json')}

pp = ProjectPoints(fpp, sam_files)
display(pp.df)

gid   config
0       2114919  onshore
1       2114920  onshore
2       2114921  onshore
3       2114922  onshore
4       2114923  onshore
...         ...      ...
124402  2239321  onshore
124403  2239322  onshore
124404  2239323  onshore
124405  2239324  onshore
124406  2239325  onshore

[124407 rows x 2 columns]

2) From a list or slice of gids and a single ``SAM`` configuration file:

In [2]:
import os
from reV import TESTDATADIR
from reV.config.project_points import ProjectPoints

sites = slice(0, 100)  # or
sites = [0, 5, 6, 9, 12]

sam_file = os.path.join(TESTDATADIR, 'SAM/wind_gen_standard_losses_0.json')

pp = ProjectPoints(sites, sam_file)
display(pp.df)

gid                                             config
0    0  /Users/mrossol/Git_Repos/reV/tests/data/SAM/wi...
1    5  /Users/mrossol/Git_Repos/reV/tests/data/SAM/wi...
2    6  /Users/mrossol/Git_Repos/reV/tests/data/SAM/wi...
3    9  /Users/mrossol/Git_Repos/reV/tests/data/SAM/wi...
4   12  /Users/mrossol/Git_Repos/reV/tests/data/SAM/wi...

3) From a pair or pairs of latitude and longitude coordinates and a single
   ``SAM`` configuration file (NOTE: access to the resource file to be used
   for ``reV Gen`` or ``reV Econ`` is needed to find the associated resource
   gids):

In [4]:
import os
import numpy as np
from reV import TESTDATADIR
from reV.config.project_points import ProjectPoints

# A single (lat, lon) coordinate
lat_lons = [41.77, -71.74]
# Or a n x 2 list or array of (lat, lon) coordinates
lat_lons = np.array([[ 41.77, -71.74],
                    [ 41.73, -71.7 ],
                    [ 42.01, -71.7 ],
                    [ 40.97, -71.74],
                    [ 41.49, -71.78]])

res_file = os.path.join(TESTDATADIR, 'nsrdb/', 'ri_100_nsrdb_2012.h5')
sam_file = os.path.join(TESTDATADIR, 'SAM/naris_pv_1axis_inv13.json')

pp = ProjectPoints.lat_lon_coords(lat_lons, res_file, sam_file)
display(pp.df)

/Users/mrossol/Git_Repos/reV/reV/config/project_points.py:576: UserWarning: WARNING: points are not in sequential order and will be sorted! The original order is being preserved under column "points_order"
  warn(msg)


gid                                             config  points_order  \
0   31  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             4   
1   41  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             3   
2   49  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             0   
3   67  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             1   
4   79  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             2   

   latitude  longitude  
0     41.49     -71.78  
1     40.97     -71.74  
2     41.77     -71.74  
3     41.73     -71.70  
4     42.01     -71.70

4) A geographic region or regions and a single ``SAM`` configuration file
   (NOTE: access to the resource file to be used for ``reV Gen`` or
   ``reV Econ`` is needed to find the associated resource gids):

In [5]:
import os
from reV import TESTDATADIR
from reV.config.project_points import ProjectPoints

# Of form {region : region_column}
regions = {'Rhode Island': 'state'} 
# or
regions = {'Providence': 'county', 'Kent': 'county'}

res_file = os.path.join(TESTDATADIR, 'nsrdb/', 'ri_100_nsrdb_2012.h5')
sam_file = os.path.join(TESTDATADIR, 'SAM/naris_pv_1axis_inv13.json')

pp = ProjectPoints.regions(regions, res_file, sam_file)
display(pp.df)

/Users/mrossol/Git_Repos/reV/reV/config/project_points.py:576: UserWarning: WARNING: points are not in sequential order and will be sorted! The original order is being preserved under column "points_order"
  warn(msg)


gid                                             config  points_order  \
0    13  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             0   
1    14  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             1   
2    17  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            23   
3    18  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             2   
4    19  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             3   
5    25  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            24   
6    26  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            25   
7    29  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             4   
8    32  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             5   
9    33  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             6   
10   36  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            26   
11   38  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             7   
12   40  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             8   
13   44  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            27   
14   48  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...             9   
15   49  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            10   
16   52  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            11   
17   53  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            12   
18   55  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            13   
19   59  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            28   
20   67  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            14   
21   68  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            29   
22   69  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            15   
23   71  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            16   
24   77  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            17   
25   78  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            18   
26   82  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            19   
27   83  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            20   
28   87  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            30   
29   90  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            31   
30   94  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            21   
31   96  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            22   
32   98  /Users/mrossol/Git_Repos/reV/tests/data/SAM/na...            32   

        county  
0   Providence  
1   Providence  
2         Kent  
3   Providence  
4   Providence  
5         Kent  
6         Kent  
7   Providence  
8   Providence  
9   Providence  
10        Kent  
11  Providence  
12  Providence  
13        Kent  
14  Providence  
15  Providence  
16  Providence  
17  Providence  
18  Providence  
19        Kent  
20  Providence  
21        Kent  
22  Providence  
23  Providence  
24  Providence  
25  Providence  
26  Providence  
27  Providence  
28        Kent  
29        Kent  
30  Providence  
31  Providence  
32        Kent

## Command Line Interface (CLI)

Options 3 and 4 above can be run from the Command Line using the
[reV-project-points](https://nrel.github.io/reV/reV/reV.config.cli_project_points.html#rev-project-points)
CLI

```bash
out_file='./project_points.csv'

TESTDATADIR=.../tests/data
res_file=${TESTDATADIR}/nsrdb/ri_100_nsrdb_2012.h5
sam_file=${TESTDATADIR}/SAM/naris_pv_1axis_inv13.json

reV-project-points --fpath=${out_file} --res_file=${res_file} --sam_file=${sam_file} from-lat-lons --lat_lon_coords 41.77 -71.74
```

or

```bash
out_file='./project_points.csv'

TESTDATADIR=.../tests/data
res_file=${TESTDATADIR}/nsrdb/ri_100_nsrdb_2012.h5
sam_file=${TESTDATADIR}/SAM/naris_pv_1axis_inv13.json

reV-project-points --fpath=${out_file} --res_file=${res_file} --sam_file=${sam_file} from-regions --region="Rhode Island" --region_col=state
```

In [36]:
!reV-project-points --help

Usage: reV-project-points [OPTIONS] COMMAND [ARGS]...

  reV ProjectPoints generator

Options:
  --version             Show the version and exit.
  -f, --fpath PATH      .csv file path to save project points to (required)
                        [required]

  -rf, --res_file TEXT  Filepath to single resource file, multi-h5 directory,
                        or /h5_dir/prefix*suffix (required)  [required]

  -sf, --sam_file PATH  SAM config file (required)  [required]
  -v, --verbose         Flag to turn on debug logging. Default is not verbose.
  --help                Show this message and exit.

Commands:
  from-lat-lons  Convert latitude and longitude coordinates to ProjectPoints
  from-regions   Extract ProjectPoints for given geographic regions
